name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
      - name: ROM
      image: baalajimaestro/android_build:latest

    run: bash ./setup.sh
